# Generated by Django 2.0.3 on 2018-04-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Model1', models.CharField(max_length=100)),
                ('Test_Model2', models.CharField(max_length=100)),
            ],
        ),
    ]
