# Generated by Django 2.0.3 on 2018-04-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_Model1', models.CharField(max_length=100)),
                ('Test_Model2', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Test_Model',
        ),
    ]
