# Generated by Django 2.0.3 on 2018-04-28 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20180413_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='Test_Model2',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='Test_Model1',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='ip_address',
            field=models.CharField(default='ABC', max_length=120),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
