# Generated by Django 2.0.3 on 2018-04-28 10:20

from django.db import migrations, models
import start.models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_auto_20180428_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='ip',
            field=models.CharField(default=start.models.get_ip, max_length=100),
        ),
    ]
