# Generated by Django 2.0.3 on 2018-04-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_auto_20180428_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='ip',
            field=models.CharField(default='hero', max_length=100),
        ),
    ]
