# Generated by Django 2.0.3 on 2018-04-30 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0007_auto_20180430_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
