# Generated by Django 2.0.3 on 2018-04-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0008_newsletter_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='timestamp',
        ),
    ]
