# Generated by Django 2.0.3 on 2018-04-30 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0009_remove_newsletter_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='heading',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
