# Generated by Django 2.0.3 on 2018-04-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0010_newsletter_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
            ],
        ),
    ]
