# Generated by Django 2.0.3 on 2018-05-01 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0012_auto_20180430_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='callMe',
            new_name='heading',
        ),
    ]
