# Generated by Django 2.0.3 on 2018-05-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0013_auto_20180501_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='heading',
            new_name='notheading',
        ),
    ]
