# Generated by Django 2.0.3 on 2018-05-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0014_auto_20180501_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='notheading',
            new_name='heading',
        ),
    ]
