# Generated by Django 2.0.3 on 2018-05-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0018_auto_20180502_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='file',
            new_name='fileToUpload',
        ),
    ]
