# Generated by Django 2.0.3 on 2018-05-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0019_auto_20180502_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='fileToUpload',
            new_name='File',
        ),
    ]
