# Generated by Django 2.0.3 on 2018-05-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0022_auto_20180502_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='File',
            new_name='xyz',
        ),
    ]
