# Generated by Django 2.0.3 on 2018-05-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0023_auto_20180502_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='xyz',
            new_name='name',
        ),
    ]
