# Generated by Django 2.0.3 on 2018-05-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0024_auto_20180502_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
