# Generated by Django 2.0.3 on 2018-05-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0025_auto_20180502_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
