# Generated by Django 2.0.3 on 2018-05-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0026_auto_20180502_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='name',
            new_name='fileKey',
        ),
    ]
