# Generated by Django 2.0.3 on 2018-05-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0027_auto_20180502_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='fileKey',
            new_name='file',
        ),
    ]
