# Generated by Django 2.0.3 on 2018-05-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0028_auto_20180503_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='file',
            new_name='filesend',
        ),
    ]
