# Generated by Django 2.0.3 on 2018-05-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0029_auto_20180503_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='filesend',
            new_name='file',
        ),
    ]
