# Generated by Django 2.0.3 on 2018-05-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0030_auto_20180503_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='htmlupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(max_length=200)),
            ],
        ),
    ]
