# Generated by Django 2.0.3 on 2018-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0031_htmlupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlupload',
            name='file',
            field=models.TextField(max_length=3000),
        ),
    ]
