# Generated by Django 2.0.3 on 2018-05-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0032_auto_20180503_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='newshtmlupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=200, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='htmlupload',
            name='file',
            field=models.TextField(max_length=1000000000),
        ),
    ]
